### ISSUE TITLE
header error

### ISSUE THREAD

**Issue by AdeenaLathiya** [odziem/planet-csv-deno#1]
I have the exact same code, but my header has an error.
The error says: 
```
error: TS2345 [ERROR]: Argument of type '{ header: boolean; comment: string; }' is not assignable to parameter of type 'ParseOptions'.
  Object literal may only specify known properties, and 'header' does not exist in type 'ParseOptions'.
        header: true,
        ~~~~~~~~~~~~
    at file:///home/adeena/Desktop/CSV-EXAMPLE/mod.ts:18:9
```
Please help me. Here is a screenshot
![Screenshot from 2020-10-15 16-40-28](https://user-images.githubusercontent.com/57405860/96118597-2aaa7780-0f05-11eb-957a-11eade64671f.png)

**Comment by magician20** [comment]
Correct code  >> `parse(bufReader, { skipFirstRow: false, comment: "#" });`

Parse lib has been updated, that's why the error (header doesn't exist anymore).

**Comment by AdeenaLathiya** [comment]
Thankyou! It worked!

**Comment by AdeenaLathiya** [comment]
Thank you! It worked.
